const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    VERIFY_TOKEN_REQUEST: 'VERIFY_TOKEN_REQUEST',
    VERIFY_TOKEN_SUCCESS: 'VERIFY_TOKEN_SUCCESS',
    VERIFY_TOKEN_ERROR: 'VERIFY_TOKEN_ERROR'
}

export default authConstants;