const hodgkinHuxleyConstants = {
    SET_MORPHOLOGY: 'SET_MORPHOLOGY',
    ADD_MOD_FILE: 'ADD_MOD_FILE',
    REMOVE_MOD_FILE: 'REMOVE_MOD_FILE',
    ADD_ELECTROPHYSIOLOGY: 'ADD_ELECTROPHYSIOLOGY',
    REMOVE_ELECTROPHYSIOLOGY: 'REMOVE_ELECTROPHYSIOLOGY',
    CLEAR: 'CLEAR'
}

export default hodgkinHuxleyConstants